type ResponseCode =
  | 'ADMIN_MEMBER_LOGIN_FAILED'
  | 'ADMIN_MEMBER_NOT_FOUND'
  | 'ADMIN_MEMBER_SIGN_UP_REQUEST_INVALID'
  | 'ADMIN_MEMBER_USERNAME_DUPLICATED'
  | 'APPLICANT_NOT_FOUND'
  | 'APPLICATION_ALREADY_SUBMITTED'
  | 'APPLICATION_CONFIRMATION_UPDATE_INVALID'
  | 'APPLICATION_CREATION_REQUEST_INVALID'
  | 'APPLICATION_FORM_ALREADY_EXIST'
  | 'APPLICATION_FORM_DELETE_NOT_ALLOWED'
  | 'APPLICATION_FORM_MODIFICATION_NOT_ALLOWED'
  | 'APPLICATION_FORM_NOT_FOUND'
  | 'APPLICATION_MODIFICATION_NOT_ALLOWED'
  | 'APPLICATION_NOT_FOUND'
  | 'APPLICATION_PRIVACY_POLICY_NOT_AGREED'
  | 'APPLICATION_SUBMIT_REQUEST_INVALID'
  | 'BAD_REQUEST'
  | 'FORBIDDEN'
  | 'INTERNAL_SERVER_ERROR'
  | 'INTERVIEW_TIME_INVALID'
  | 'NOTIFICATION_FAILED_TO_SEND_SMS'
  | 'NOTIFICATION_NOT_FOUND'
  | 'NOTIFICATION_REQUEST_INVALID'
  | 'NOT_FOUND'
  | 'RECRUITMENT_SCHEDULE_DUPLICATED'
  | 'RECRUITMENT_SCHEDULE_NOT_FOUND'
  | 'SUCCESS'
  | 'TEAM_NOT_FOUND'
  | 'UNAUTHORIZED';

export interface BaseResponse<T> {
  code: ResponseCode;
  data: T;
  message: string;
  page: {
    number: number;
    size: number;
    totalCount: number;
  };
}

export interface BaseRequest {
  accessToken?: string;
}
